require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
platform :ios, '10.0'

target 'admin_panel' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'admin_panelTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.3.0' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'admin_panel-tvOS' do
  # Pods for admin_panel-tvOS

  target 'admin_panel-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
